const router = require('koa-router')()
module.exports = (app) => {
    router.get( '/', app.controller.home.index )
    router.get('/home', app.controller.home.home)
    router.get('/home/:id/:name', app.controller.home.homeParams)
    router.get('/user', app.controller.home.login)
    router.post('/user/register', app.controller.home.register)
    router.get('/admin', app.controller.admin.getAdminInfo)
    router.get('/tags', app.controller.tag.getTagInfo)
    router.get('/lesson/list', app.controller.lesson.getLessonInfo)
    router.get('/lesson/:tid', app.controller.lesson.getTagLessonInfo)
    router.get('/lessons/recommend', app.controller.lesson.getRecommendLessonInfo)
    router.get('/lessons/hot', app.controller.lesson.getHotLessonInfo)
    router.get('/video/:lid', app.controller.video.getVideoInfo)
    app.use(router.routes()).use(router.allowedMethods())
}